### ISSUE TITLE
Solar from Inverter RS doesn't show in Brief/Overview and Device List 

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1574]
When the solar comes from a RS Inverter, it does not appear in the Brief and Overview pages; there is an empty space where the solar gauge and solar widget should be.

Also, in the Device List, the total power for the inverter is "0W", even though clicking on the device shows a non-zero value for the "PV" item.

Reproducible on https://vrm.victronenergy.com/installation/491097/overview

See slack thread: https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1728027496342769

## Further investigation

The problem here is that `Global.solarChargers.model` is generated from the `solarcharger` and `multi` services, as per `data/dbus/SolarChargersImpl.qml` and `data/mqtt/SolarChargersImpl.qml`. This is not correct because:

- It omits Inverter RS devices that provide solar data (i.e. `inverter` services with `/NrOfTrackers > 0`)
- It should only add Multi RS services if they have `/NrOfTrackers > 0`.

The main solar properties should be extracted from `SolarCharger.qml` into a base type like `SolarDevice.qml` or `PvDevice.qml`. Then, objects of this type can be created from solarcharger, multi or inverter services where `/NrOfTrackers > 0`, and added to the global list of solar devices.

Additionally, the solar drilldown should show a common solar-device-type page with the common solar data, and a "Product page" sub-page link that takes the user to the Device List page for that service. This is similar to the Inverter/Charger drilldown, which shows a common page for all inverter/charger devices, and has a "Product page" sub-page link to the service-specific device pages.

## Tasks

- [x] Add `PageSolarCharger.qml` ported from gui-v1, and open it from `SolarChargerPage.qml`  with a "Product page" link. https://github.com/victronenergy/gui-v2/pull/1864
- [x] Change `SolarChargerPage.qml` to generic `SolarDevicePage.qml` without the solarcharger-specific list items (i.e. "link" and "network" information). https://github.com/victronenergy/gui-v2/pull/1864
- [x] Add `SolarDevice.qml` base type with the solar-related properties common to `solarcharger`, `multi` and `inverter` services. Add `Global.solarDevices.model` that contains all `solarcharger` devices, as well as any  `multi` and `inverter` devices with `/NrOfTrackers > 0`. https://github.com/victronenergy/gui-v2/pull/1871
- [x] Replace all uses of `Global.solarChargers` with `Global.solarDevices`, and remove Global.solarChargers. This includes the uses in the Overview solar drilldown list, which should then show all `solarcharger` devices, as well as any  `multi` and `inverter` devices with `/NrOfTrackers > 0`. https://github.com/victronenergy/gui-v2/pull/1871

## Testing/verification:

- Overview solar drilldown should show:
    - all `solarcharger` services
    - any `multi` and `inverter` services with `/NrOfTrackers > 0`
    - all `pvinverter` services (as per existing functionality, under a separate header)
- When any of the above devices are clicked in the list, the user should be taken to the `SolarDevicePage` that shows the common solar-related data.
- Brief page should show the solar generated by `inverter` and `multi` services that have `/NrOfTrackers > 0`, if there are no `solarcharger` services present.
- Device List: clicking on a solar charger should show the `PageSolarCharger` similar to the gui-v1 page for solar chargers, rather than the `SolarDevicePage`. 
- Device List: inverters with solar data should show the total power, if PV power has been generated.

These systems can be used for verification:

- Has Inverter RS services with solar data: https://vrm.victronenergy.com/installation/40911/overview
- Has Multi RS services with solar data: https://vrm.victronenergy.com/installation/491097/dashboard

**Comment by blammit** [comment]
This is happening because the solar info is only shown on the Brief and Overview pages when there are `solarcharger` or `pvinverter` services present. On this installation, only `inverter` services are present.

**Comment by mpvader** [comment]
Don’t forget .multi.

**Comment by blammit** [comment]
Sorry, yes `multi` is already included as part of solar devices, forgot to put that in the comment.

**Comment by blammit** [comment]
Updated the description with notes for investigation, tasks and testing/verification.

**Comment by blammit** [comment]
Changes have been merged.
